version: '3.7'
services:
  web:
    build:
      context: ./docker/python
    command: >
      sh -c "python3 manage.py makemigrations tattoo_shop
      && python3 manage.py migrate
      && python3 manage.py runserver 0.0.0.0:8000"

    volumes:
      - ./backend:/app/
    restart: always
    ports:
      - 8001:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    container_name: db_tattoo
    ports:
      - 5431:5432
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  redis_service:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD
      - REDIS_PASSWORD
    container_name: redis_tattoo
    restart: always

  worker:
    build:
      context: ./docker/python
    container_name: worker_tattoo
    env_file:
      - .env
    user: nobody
    depends_on:
      - redis_service
    command: celery -A backend.celery worker -l DEBUG
    volumes:
      - ./backend:/app/

  beat:
    build:
      context: ./docker/python
    env_file:
      - .env
    container_name: beat_tattoo
    depends_on:
      - redis_service
      - worker
    command: celery -A backend.celery beat --schedule=/tmp/celerybeat-schedule --loglevel=INFO --pidfile=/tmp/celerybeat.pid
    volumes:
      - ./app:/app/
volumes:
  postgres_data: