version: '3.7'
services:
  web:
    build: ./backend
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/home/posttsoi/web/backend
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
