import { root } from '../root';
import type { AllProducts } from './types';
import { ProductCategories } from './types';

const mockProds = {
  TShirt: [
    {
      id: 1,
      title: 'Футболка классная, белая',
      description:
        'Классная белая футболка из хлопка с рисунком на спине. Рисунок крутого кота - ручной работы, краска черная, краска красная.',
      price: '2000.000',
      quantity: 3,
      slug: '1',
      image: null,
      size: 'M',
      colour: 'W',
      category: 1,
    },
    {
      id: 2,
      title: 'sdfdd',
      description: 'sddddf',
      price: '0.02',
      quantity: 3,
      slug: '22f',
      image: null,
      size: 'M',
      colour: 'W',
      category: 1,
    },
    {
      id: 14,
      title: 'sdfsdssd',
      description: 'sdsdfsf',
      price: '0.02',
      quantity: 3,
      slug: '1dfsf',
      image: null,
      size: 'M',
      colour: 'W',
      category: 1,
    },
  ],
  Sticker: [
    {
      id: 23,
      title: '2234',
      description: '234',
      price: '2.99',
      slug: '1essf',
      image: null,
      quantity: 3,
      category: 2,
    },
    {
      id: 23,
      title: '2234',
      description: '234',
      price: '2.99',
      slug: '1essf',
      image: null,
      quantity: 3,
      category: 2,
    },
    {
      id: 23232,
      title: '223sdgsdg4',
      description: '234',
      price: '2.99',
      slug: '1essf',
      image: null,
      quantity: 3,
      category: 2,
    },
  ],
  TattooSketch: [
    {
      id: 13443,
      title: 'Test',
      description: 'Test description for content',
      vacant: true,
      image: 'https://placekitten.com/500/500',
      slug: `1`,
    },
    {
      id: 5453435,
      title: 'Test2 ывпыып',
      description:
        'Test description for content another sdgsgsdппыпыпыапап вавпвапв',
      vacant: false,
      image: 'https://placekitten.com/500/500',
      slug: `2`,
    },
    {
      id: 34435345,
      title: 'Test3',
      description: 'Test description for content third',
      vacant: true,
      image: 'https://placekitten.com/500/500',
      slug: `3`,
    },
    {
      id: 3463463,
      title: 'Test',
      description:
        'Test description for content ывпывпыв ыпыпып ыпып ывпыпвывпы ывпы ',
      vacant: true,
      image: 'https://placekitten.com/500/500',
      slug: `12`,
    },
    {
      id: 45345345,
      title: 'Test2',
      description: '',
      vacant: false,
      image: 'https://placekitten.com/500/500',
      slug: `24`,
    },
    {
      id: 199343,
      title: 'Test3',
      description: 'Test description for content third',
      vacant: true,
      image: 'https://placekitten.com/500/500',
      slug: `35`,
    },
    {
      title: 'Test',
      description: 'Test description for content',
      vacant: true,
      image: 'https://placekitten.com/500/500',
      slug: `112`,
    },
    {
      id: 122355,
      title: 'Test2 ывпыып',
      description:
        'Test description for content another sdgsgsdппыпыпыапап вавпвапв',
      vacant: false,
      image: 'https://placekitten.com/500/500',
      slug: `3332`,
    },
    {
      id: 22353525,
      title: 'Test3',
      description: 'Test description for content third',
      vacant: true,
      image: 'https://placekitten.com/500/500',
      slug: `3333`,
    },
    {
      id: 12299,
      title: 'Test',
      description:
        'Test description for content ывпывпыв ыпыпып ыпып ывпыпвывпы ывпы ',
      vacant: true,
      image: 'https://placekitten.com/500/500',
      slug: `13333`,
    },
    {
      id: 13592539,
      title: 'Test2',
      description: '',
      vacant: false,
      image: 'https://placekitten.com/500/500',
      slug: `23333`,
    },
    {
      id: 2359259235,
      title: 'Test3',
      description: 'Test description for content third',
      vacant: true,
      image: 'https://placekitten.com/500/500',
      slug: `33333`,
    },
    {
      id: 2395259235,
      title: 'Test',
      description: 'Test description for content',
      vacant: true,
      image: 'https://placekitten.com/500/500',
      slug: `13333`,
    },
    {
      id: 2392359235,
      title: 'Test2 ывпыып',
      description:
        'Test description for content another sdgsgsdппыпыпыапап вавпвапв',
      vacant: false,
      image: 'https://placekitten.com/500/500',
      slug: `233333`,
    },
    {
      id: 23235235,
      title: 'Test3',
      description: 'Test description for content third',
      vacant: true,
      image: 'https://placekitten.com/500/500',
      slug: `333343`,
    },
    {
      id: 235235235,
      title: 'Test',
      description:
        'Test description for content ывпывпыв ыпыпып ыпып ывпыпвывпы ывпы ',
      vacant: true,
      image: 'https://placekitten.com/500/500',
      slug: `16`,
    },
    {
      id: 2352525,
      title: 'Test2',
      description: '',
      vacant: false,
      image: 'https://placekitten.com/500/500',
      slug: `25`,
    },
    {
      id: 9012244,
      title: 'Test3',
      description: 'Test description for content third',
      vacant: true,
      image: 'https://placekitten.com/500/500',
      slug: `325`,
    },
    {
      id: 903592530925,
      title: 'Test',
      description:
        'Test description for content ывпывпыв ыпыпып ыпып ывпыпвывпы ывпы ',
      vacant: true,
      image: 'https://placekitten.com/500/500',
      slug: `1134567`,
    },
    {
      id: 235235235235,
      title: 'Test',
      description:
        'Test description for content ывпывпыв ыпыпып ыпып ывпыпвывпы ывпы ',
      vacant: true,
      image: 'https://placekitten.com/500/500',
      slug: `133556`,
    },
  ],
};

export const $allProducts = root.createStore<AllProducts>(mockProds);
export const $tattoos = $allProducts.map((s) => s.TattooSketch || []);
export const $stickers = $allProducts.map((s) => s.Sticker || []);
export const $tshirts = $allProducts.map((s) => s.TShirt || []);
